import type { CSSProperties } from "react";

/** Co-located styles for OnboardingTourPage — mirrors ProjectContextPage's shape. */
export const s = {
  page: { padding: "24px 32px 60px", maxWidth: 1200, margin: "0 auto" } satisfies CSSProperties,
  header: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 14,
    marginBottom: 16,
  } satisfies CSSProperties,
  headerText: { flex: 1 } satisfies CSSProperties,
  h1: { fontSize: 24, fontWeight: 700, letterSpacing: "-0.02em" } satisfies CSSProperties,
  subtitle: { fontSize: 13, color: "var(--text-secondary)", marginTop: 4 } satisfies CSSProperties,
  headerActions: { display: "flex", alignItems: "center", gap: 8, flexShrink: 0 } satisfies CSSProperties,
  banner: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "10px 14px",
    borderRadius: 8,
    background: "var(--warn-bg)",
    color: "var(--warn)",
    fontSize: 13,
    fontWeight: 500,
    marginBottom: 20,
  } satisfies CSSProperties,
  layout: {
    display: "grid",
    gridTemplateColumns: "200px 1fr",
    gap: 24,
    alignItems: "start",
  } satisfies CSSProperties,
  nav: {
    position: "sticky",
    top: 16,
    display: "flex",
    flexDirection: "column",
    gap: 2,
  } satisfies CSSProperties,
  navLabel: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.06em",
    color: "var(--text-muted)",
    textTransform: "uppercase",
    marginBottom: 6,
  } satisfies CSSProperties,
  navItem: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "6px 8px",
    borderRadius: 6,
    fontSize: 13,
    color: "var(--text-secondary)",
    background: "none",
    border: "none",
    cursor: "pointer",
    textAlign: "left",
    width: "100%",
  } satisfies CSSProperties,
  cards: { display: "flex", flexDirection: "column", gap: 16 } satisfies CSSProperties,
  card: {
    border: "1px solid var(--border)",
    borderRadius: 10,
    background: "var(--bg-surface)",
    overflow: "hidden",
    scrollMarginTop: 16,
  } satisfies CSSProperties,
  cardHeader: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "13px 16px",
    cursor: "pointer",
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  cardTitle: { fontWeight: 600, fontSize: 14, flex: 1 } satisfies CSSProperties,
  cardBody: { padding: "0 16px 18px" } satisfies CSSProperties,
} as const;
