/**
 * ci module — GitHub Actions workflow generation (SPEC-08 T3, AC-11).
 *
 * Pure function: given the wizard's Configure-step choices, returns the full
 * `.github/workflows/devdigest-review.yml` text. No I/O, no container.
 *
 * NFR / security invariants this MUST keep (see `docs/specs/SPEC-08-export-to-ci.md`
 * NFR section + the `security` skill applied while writing this file):
 *  - `on: pull_request` ONLY — never `pull_request_target` (fork PRs never get
 *    privileged secrets).
 *  - The run step is `run: node .devdigest/runner/index.js` — never
 *    `uses: devdigest/review-action@v1` (that action does not exist).
 *  - No PR title/body/branch name is ever interpolated into a `run:` block —
 *    every step here is a static string.
 *  - `actions/checkout` and `actions/upload-artifact` are pinned to a full
 *    commit SHA (trailing `# vX.Y.Z` comment for humans), never a floating
 *    tag like `@v4`.
 *  - `OPENROUTER_API_KEY` is only ever wired via `secrets.OPENROUTER_API_KEY`
 *    into `env:`, never hardcoded or passed as a `run:` argument (keeps it
 *    out of the Actions log).
 */

/** Semantic version of THIS generator's output — bumped whenever the
 *  template below changes. Shown on the CI tab's installations list
 *  (`ci_installations.workflow_version`, AC-33). Not a content hash — a
 *  human-meaningful version number was the explicit choice for this plan
 *  (see the Development Plan's Constraints on this open question). */
export const WORKFLOW_GENERATOR_VERSION = '1.0.0';

// Pinned by full commit SHA, never a floating tag (NFR above). Re-verify
// against the upstream release page before bumping either version — these
// were resolved from memory at authoring time, not fetched live.
const CHECKOUT_ACTION_SHA = '11bd71901bbe5b1630ceea73d27597364c9af683'; // actions/checkout v4.2.2
const UPLOAD_ARTIFACT_ACTION_SHA = '50769540e7f4bd5e21e526ee35c689e35e0d6874'; // actions/upload-artifact v4.4.0

export type PostAs = 'github_review' | 'pr_comment' | 'none';

export interface GenerateWorkflowInput {
  /** `on.pull_request.types` — whatever the Configure step's checkboxes
   *  resolved to (AC-13); passed through as-is, not re-validated here. */
  triggers: string[];
  postAs: PostAs;
}

/** Double-quoted YAML scalar (see `manifest.ts`'s identical helper — kept
 *  local/duplicated rather than shared to keep this file a standalone pure
 *  function with no cross-file coupling inside the module). */
function yamlDoubleQuoted(value: string): string {
  return JSON.stringify(value);
}

/**
 * Generate `.github/workflows/devdigest-review.yml` (AC-11). `postAs` is
 * baked in as a plain static string env var (`DEVDIGEST_POST_AS`) — this is
 * the resolution of `agent-runner/insights/INSIGHTS.md`'s open question
 * ("should post_as be folded into AgentManifest, or threaded through the
 * workflow as an env var?"): threaded through the workflow, never a secret,
 * never templated from any untrusted input.
 */
export function generateWorkflowYaml(input: GenerateWorkflowInput): string {
  const typesLine =
    input.triggers.length > 0 ? `    types: [${input.triggers.join(', ')}]` : '    types: []';

  const permissionsLines = ['permissions:', '  contents: read'];
  if (input.postAs !== 'none') permissionsLines.push('  pull-requests: write');

  const lines = [
    '# Generated by DevDigest (export-to-ci). Editable, but re-verify the',
    '# pinned action SHAs against the upstream release before bumping a version.',
    'name: DevDigest Review',
    '',
    'on:',
    '  pull_request:',
    typesLine,
    '',
    ...permissionsLines,
    '',
    'jobs:',
    '  review:',
    '    runs-on: ubuntu-latest',
    '    steps:',
    `      - uses: actions/checkout@${CHECKOUT_ACTION_SHA} # v4.2.2`,
    '      - name: Run DevDigest review',
    '        run: node .devdigest/runner/index.js',
    '        env:',
    '          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}',
    '          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}',
    `          DEVDIGEST_POST_AS: ${yamlDoubleQuoted(input.postAs)}`,
    '      - if: always()',
    `        uses: actions/upload-artifact@${UPLOAD_ARTIFACT_ACTION_SHA} # v4.4.0`,
    '        with:',
    '          name: devdigest-result',
    '          path: devdigest-result.json',
    '          if-no-files-found: ignore',
    '',
  ];
  return lines.join('\n');
}
